// Generated by `specs storybook` — rewritten on every publish. Placeholder:
// the Analysis section holds its place until the analysis pages land.
import * as React from 'react';
import type { Meta, StoryObj } from '@storybook/react';

const ADDON_ID = 'specs/framework-tabs';
const pageParameters = {
  previewTabs: {
    canvas: { title: 'Page' },
    [`${ADDON_ID}/webcomponents`]: { hidden: true },
    [`${ADDON_ID}/specs`]: { hidden: true },
  },
};

const Analysis = () => (
  <div style={{ maxWidth: 640, font: '16px/1.6 system-ui, sans-serif' }}>
    <h1 style={{ marginTop: 0 }}>Analysis</h1>
    <p>Not built yet. This section will hold the reports `specs analyze` writes:</p>
    <ul>
      <li>Props across components</li>
      <li>Styling and token usage</li>
      <li>Dependencies</li>
      <li>Key naming</li>
    </ul>
  </div>
);

const meta = {
  title: 'Analysis/Overview',
  component: Analysis,
  parameters: { layout: 'padded', ...pageParameters },
} satisfies Meta<typeof Analysis>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Page: Story = { name: 'Overview' };
