// Generated by `specs storybook publish`. Do not edit — rewritten every run;
// to take control, copy to content-overrides/analysis/ (see the docs).
//
// One analysis, two tabs: Report (the dashboard — not built yet) and Specs
// (the analysis's own YAML, fetched from the statically served specs/ tree).
import * as React from 'react';
import type { Meta, StoryObj } from '@storybook/react';

const FILES: string[] = {{ANALYSIS_FILES}};

const tabStyle = (active: boolean): React.CSSProperties => ({
  padding: '10px 16px',
  border: 'none',
  background: 'none',
  cursor: 'pointer',
  font: 'inherit',
  fontWeight: active ? 700 : 400,
  borderBottom: active ? '2px solid currentColor' : '2px solid transparent',
  opacity: active ? 1 : 0.7,
});

function YamlFile({ file }: { file: string }) {
  const [text, setText] = React.useState<string | null>(null);
  React.useEffect(() => {
    let live = true;
    fetch(`/specs/_analysis/${file}`)
      .then((r) => (r.ok ? r.text() : `# ${r.status} — could not load ${file}`))
      .then((t) => live && setText(t))
      .catch((e) => live && setText(`# ${String(e)}`));
    return () => { live = false; };
  }, [file]);
  if (text === null) return <p>Loading {file}…</p>;
  return (
    <pre style={{ overflow: 'auto', maxHeight: '70vh', padding: 16, fontSize: 12, lineHeight: 1.5, background: 'rgba(0,0,0,0.03)', borderRadius: 4 }}>
      {text}
    </pre>
  );
}

function SpecsTab() {
  const [file, setFile] = React.useState(FILES[0]);
  return (
    <div>
      {FILES.length > 1 && (
        <div style={{ display: 'flex', gap: 4, borderBottom: '1px solid rgba(0,0,0,0.1)', marginBottom: 12 }}>
          {FILES.map((f) => (
            <button key={f} style={tabStyle(f === file)} onClick={() => setFile(f)}>
              {f.replace(/^{{ANALYSIS_ID}}\.?/, '') || f}
            </button>
          ))}
        </div>
      )}
      <YamlFile file={file} />
    </div>
  );
}

function {{ANALYSIS_TITLE}}Page() {
  const [tab, setTab] = React.useState<'report' | 'specs'>('report');
  return (
    <>
      <h1>{{ANALYSIS_TITLE}}</h1>
      <div style={{ display: 'flex', gap: 4, borderBottom: '1px solid rgba(0,0,0,0.1)', margin: '16px 0' }}>
        <button style={tabStyle(tab === 'report')} onClick={() => setTab('report')}>Report</button>
        <button style={tabStyle(tab === 'specs')} onClick={() => setTab('specs')}>Specs</button>
      </div>
      {tab === 'report' ? (
        <p style={{ opacity: 0.7 }}>
          The {{ANALYSIS_TITLE}} report dashboard is not built yet. The analysis data it
          will summarize is on the Specs tab, and stays a durable file under{' '}
          <code>specs/_analysis/</code> either way.
        </p>
      ) : (
        <SpecsTab />
      )}
    </>
  );
}

const meta = {
  title: 'Analysis/{{ANALYSIS_TITLE}}',
  parameters: { docs: { page: {{ANALYSIS_TITLE}}Page } },
} satisfies Meta;

export default meta;
export const Page: StoryObj = { render: () => <{{ANALYSIS_TITLE}}Page /> };
