// Generated by `specs storybook` — rewritten on every publish. To take control
// of this page, copy it to content-overrides/foundations/Color.stories.tsx and
// edit the copy; it then always wins and publish never touches it.
//
// CSF rather than MDX: a docs entry only carries `previewTabs` from CSF meta
// parameters, so an MDX page cannot opt out of the component framework tabs.
import * as React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
// Via the workspace-anchored path (not './data/…') so a copy of this file in
// content-overrides/foundations/ keeps reading the published data.
import data from '../../content/foundations/data/colors.json';

// The framework tabs are views of one component; this page opts out.

interface Swatch {
  name: string;
  leaf: string;
  value: string | null;
  via: string | null;
  description: string;
  unresolved: string | null;
}
type Layout = 'stack' | 'row' | 'group';
interface Row {
  /** Null when the row is a single swatch carrying its own name. */
  label: string | null;
  swatches: Swatch[];
}

const layoutConfig = (data as { layout?: { default?: Layout; overrides?: Record<string, Layout> } }).layout ?? {};
const DEFAULT_LAYOUT: Layout = layoutConfig.default ?? 'group';
const LAYOUTS: Record<string, Layout> = layoutConfig.overrides ?? {};

function layoutFor(collection: string, group: string): Layout {
  return LAYOUTS[`${collection}/${group}`] ?? LAYOUTS[collection] ?? DEFAULT_LAYOUT;
}

/** The folder a swatch sits in — its name without the leaf. */
function folder(name: string): string {
  const segments = name.split('/');
  return segments.length > 1 ? segments.slice(0, -1).join('/') : name;
}

/**
 * Steps in a ramp are named `07`, `44`, `100`. Sorted as text, `07` lands after
 * `96`; sort numerically when every leaf in the row is a number. The displayed
 * name keeps its padding.
 */
function orderRow(swatches: Swatch[]): Swatch[] {
  const numeric = swatches.every((s) => /^\d+$/.test(s.leaf));
  return numeric ? [...swatches].sort((a, b) => Number(a.leaf) - Number(b.leaf)) : swatches;
}

// Past this many swatches a single row renders as unreadable slivers, so a
// larger folder wraps into successive rows of this width. A 1,000-variable
// palette dump stays scannable; a 4-member semantic folder is untouched.
const MAX_ROW = 16;

function chunked(label: string, swatches: Swatch[]): Row[] {
  if (swatches.length <= MAX_ROW) return [{ label, swatches }];
  const rows: Row[] = [];
  for (let i = 0; i < swatches.length; i += MAX_ROW) {
    rows.push({
      label: i === 0 ? `${label} (${swatches.length})` : '',
      swatches: swatches.slice(i, i + MAX_ROW),
    });
  }
  return rows;
}

function rowsFor(swatches: Swatch[], layout: Layout, group: string): Row[] {
  if (layout === 'stack') return swatches.map((s) => ({ label: null, swatches: [s] }));
  if (layout === 'row') return chunked(group, orderRow(swatches));

  // One row per lowest-level folder, in the order the payload declares them.
  const byFolder = new Map<string, Swatch[]>();
  for (const s of swatches) {
    const key = folder(s.name);
    byFolder.set(key, [...(byFolder.get(key) ?? []), s]);
  }
  return [...byFolder.entries()].flatMap(([label, list]) => chunked(label, orderRow(list)));
}

/**
 * Live swatch: the background binds to the stylesheet's custom property where
 * one exists, so switching modes in the toolbar restyles it exactly as it
 * restyles components; the caption reads the computed value and follows. A
 * swatch with no property (a collection the stylesheet does not emit, a fill
 * style) stays its published value.
 */
function useLiveValue(cssProperty: string | null, published: string | null): string | null {
  const [value, setValue] = React.useState(published);
  React.useEffect(() => {
    if (!cssProperty) return;
    const read = () => {
      const live = getComputedStyle(document.documentElement).getPropertyValue(cssProperty).trim();
      setValue(live || published);
    };
    read();
    const observer = new MutationObserver(read);
    observer.observe(document.documentElement, { attributes: true });
    return () => observer.disconnect();
  }, [cssProperty, published]);
  return value;
}

function SwatchCell({ swatch, label }: { swatch: Swatch; label: string }) {
  const value = useLiveValue(swatch.cssProperty, swatch.value);
  const background = swatch.cssProperty
    ? `var(${swatch.cssProperty}, ${swatch.value ?? 'transparent'})`
    : (swatch.value ?? 'transparent');
  return (
    <div style={{ flex: 1, minWidth: 0 }}>
      <div
        title={swatch.name}
        style={{
          height: 44,
          background,
          borderRadius: 4,
          boxShadow: 'inset 0 0 0 1px rgba(0,0,0,0.1)',
        }}
      />
      <div style={{ fontFamily: 'monospace', fontSize: 11, opacity: 0.75, marginTop: 4, textAlign: 'center', overflowWrap: 'break-word' }}>
        {label && <div>{label}</div>}
        <div>{value ?? '—'}</div>
      </div>
    </div>
  );
}

function SwatchRow({ row }: { row: Row }) {
  const single = row.label === null;
  const head = single ? row.swatches[0] : null;
  return (
    <div style={{ display: 'flex', gap: 16, alignItems: 'flex-start', padding: '10px 0', borderBottom: '1px solid rgba(0,0,0,0.06)' }}>
      <div style={{ width: 220, flexShrink: 0, paddingTop: 10 }}>
        <strong style={{ overflowWrap: 'break-word' }}>{single ? head!.name : row.label}</strong>
        <div style={{ fontSize: 12, opacity: 0.65 }}>
          {single
            ? (head!.via ?? head!.description)
            : `${row.swatches.length} ${row.swatches.length === 1 ? 'value' : 'values'}`}
        </div>
      </div>
      <div style={{ display: 'flex', gap: 8, flex: 1, minWidth: 0 }}>
        {row.swatches.map((s, i) => (
          <SwatchCell key={`${i}-${s.name}`} swatch={s} label={single ? '' : s.leaf} />
        ))}
      </div>
    </div>
  );
}

function ColorPage() {
  const sources = (data as { sources: Array<{
    source: string;
    collections: Array<{ name: string; modes: string[]; groups: Array<{ name: string; swatches: Swatch[] }> }>;
    styles: Array<{ name: string; value: string | null; description: string; unresolved: string | null }>;
  }> }).sources;

  return (
    <>
      <h1>Color</h1>
      <p>
        Every colour variable the library declares, read from the variables payload — organised by
        variable collection, then by the first level of each name, in the order the library
        declares them. Values are shown in each collection&rsquo;s default mode; where a variable
        aliases another, the target is named beneath it. Fill styles follow as their own section.
      </p>

      {sources.map((src) => (
        <div key={src.source}>
          {sources.length > 1 && <h2>Source: {src.source}</h2>}

          {src.collections.map((c, ci) => (
            // Index in the key: a library can declare two collections with one name.
            <div key={`${src.source}/${ci}/${c.name}`}>
              <h2>{c.name}</h2>
              <p style={{ opacity: 0.7 }}>
                Modes: {c.modes.join(', ')} — shown in {c.modes[0]}
              </p>

              {c.groups.map((g) => {
                const layout = layoutFor(c.name, g.name);
                const rows = rowsFor(g.swatches, layout, g.name);
                const unresolved = g.swatches.filter((s) => s.unresolved);
                return (
                  <div key={g.name}>
                    <h3>{g.name}</h3>
                    <div>
                      {rows.map((row, i) => (
                        <SwatchRow key={`${i}-${row.label ?? row.swatches[0].name}`} row={row} />
                      ))}
                    </div>
                    {unresolved.length > 0 && (
                      <div style={{ color: 'crimson' }}>
                        <p style={{ marginBottom: 4 }}>Unresolved — shown, never dropped:</p>
                        <ul style={{ marginTop: 0 }}>
                          {unresolved.map((s, ui) => (
                            <li key={`${ui}-${s.name}`}>
                              <code>{s.name}</code> — {s.unresolved}
                              {s.via ? <> (via <code>{s.via}</code>)</> : null}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          ))}

          {src.styles.length > 0 && (
            <div>
              <h2>Fill styles</h2>
              <p style={{ opacity: 0.7 }}>
                Styles are a separate source from variables — listed in the order the library
                declares them.
              </p>
              <div>
                {src.styles.map((style) => (
                  <SwatchRow
                    key={style.name}
                    row={{
                      label: null,
                      swatches: [{
                        name: style.name,
                        leaf: style.name,
                        value: style.value,
                        via: null,
                        description: style.unresolved ?? style.description,
                        unresolved: style.unresolved,
                        cssProperty: null,
                      }],
                    }}
                  />
                ))}
              </div>
            </div>
          )}
        </div>
      ))}
    </>
  );
}

const meta = {
  title: 'Foundations/Color',
  parameters: { docs: { page: ColorPage } },
} satisfies Meta;

export default meta;
export const Page: StoryObj = { render: () => <ColorPage /> };
