// Generated by `specs storybook` — rewritten on every publish. To take control
// of this page, copy it to content-overrides/foundations/Color.stories.tsx and
// edit the copy; it then always wins and publish never touches it.
//
// CSF rather than MDX: a docs entry only carries `previewTabs` from CSF meta
// parameters, so an MDX page cannot opt out of the component framework tabs.
import * as React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { ColorPalette, ColorItem } from '@storybook/blocks';
// Via the workspace-anchored path (not './data/…') so a copy of this file in
// content-overrides/foundations/ keeps reading the published data.
import data from '../../content/foundations/data/colors.json';

// The framework tabs are views of one component; this page opts out.
const ADDON_ID = 'specs/framework-tabs';
const pageParameters = {
  previewTabs: {
    canvas: { title: 'Page' },
    [`${ADDON_ID}/webcomponents`]: { hidden: true },
    [`${ADDON_ID}/specs`]: { hidden: true },
  },
};

interface Swatch {
  name: string;
  leaf: string;
  value: string | null;
  via: string | null;
  description: string;
  unresolved: string | null;
}
type Layout = 'stack' | 'row' | 'group';
interface Row {
  /** Null when the row is a single swatch carrying its own name. */
  label: string | null;
  swatches: Swatch[];
}

const layoutConfig = (data as { layout?: { default?: Layout; overrides?: Record<string, Layout> } }).layout ?? {};
const DEFAULT_LAYOUT: Layout = layoutConfig.default ?? 'group';
const LAYOUTS: Record<string, Layout> = layoutConfig.overrides ?? {};

function layoutFor(collection: string, group: string): Layout {
  return LAYOUTS[`${collection}/${group}`] ?? LAYOUTS[collection] ?? DEFAULT_LAYOUT;
}

/** The folder a swatch sits in — its name without the leaf. */
function folder(name: string): string {
  const segments = name.split('/');
  return segments.length > 1 ? segments.slice(0, -1).join('/') : name;
}

/**
 * Steps in a ramp are named `07`, `44`, `100`. Sorted as text, `07` lands after
 * `96`; sort numerically when every leaf in the row is a number. The displayed
 * name keeps its padding.
 */
function orderRow(swatches: Swatch[]): Swatch[] {
  const numeric = swatches.every((s) => /^\d+$/.test(s.leaf));
  return numeric ? [...swatches].sort((a, b) => Number(a.leaf) - Number(b.leaf)) : swatches;
}

function rowsFor(swatches: Swatch[], layout: Layout, group: string): Row[] {
  if (layout === 'stack') return swatches.map((s) => ({ label: null, swatches: [s] }));
  if (layout === 'row') return [{ label: group, swatches: orderRow(swatches) }];

  // One row per lowest-level folder, in the order the payload declares them.
  const byFolder = new Map<string, Swatch[]>();
  for (const s of swatches) {
    const key = folder(s.name);
    byFolder.set(key, [...(byFolder.get(key) ?? []), s]);
  }
  return [...byFolder.entries()].map(([label, list]) => ({ label, swatches: orderRow(list) }));
}

/**
 * A row's swatches as the `colors` object ColorItem wants, label to value.
 *
 * Keys carry a zero-width space because a plain object reorders integer-like
 * string keys into ascending numeric order and leaves non-canonical ones like
 * `07` in insertion order at the end — which silently reorders a ramp whatever
 * the array sort says. A non-integer key preserves insertion order, and the
 * character does not render.
 */
function rowColors(swatches: Swatch[]): Record<string, string> {
  const entries: Array<[string, string]> = [];
  for (const s of swatches) {
    if (s.value) entries.push([`\u200b${s.leaf}`, s.value]);
  }
  return Object.fromEntries(entries);
}

function ColorPage() {
  const sources = (data as { sources: Array<{
    source: string;
    collections: Array<{ name: string; modes: string[]; groups: Array<{ name: string; swatches: Swatch[] }> }>;
    styles: Array<{ name: string; value: string | null; description: string; unresolved: string | null }>;
  }> }).sources;

  return (
    <>
      <h1>Color</h1>
      <p>
        Every colour variable the library declares, read from the variables payload — organised by
        variable collection, then by the first level of each name, in the order the library
        declares them. Values are shown in each collection&rsquo;s default mode; where a variable
        aliases another, the target is named beneath it. Fill styles follow as their own section.
      </p>

      {sources.map((src) => (
        <div key={src.source}>
          {sources.length > 1 && <h2>Source: {src.source}</h2>}

          {src.collections.map((c, ci) => (
            // Index in the key: a library can declare two collections with one name.
            <div key={`${src.source}/${ci}/${c.name}`}>
              <h2>{c.name}</h2>
              <p style={{ opacity: 0.7 }}>
                Modes: {c.modes.join(', ')} — shown in {c.modes[0]}
              </p>

              {c.groups.map((g) => {
                const layout = layoutFor(c.name, g.name);
                const rows = rowsFor(g.swatches, layout, g.name);
                const unresolved = g.swatches.filter((s) => s.unresolved);
                return (
                  <div key={g.name}>
                    <h3>{g.name}</h3>
                    <ColorPalette>
                      {rows.map((row, i) =>
                        row.label === null ? (
                          <ColorItem
                            key={`${i}-${row.swatches[0].name}`}
                            title={row.swatches[0].name}
                            subtitle={row.swatches[0].via ?? row.swatches[0].description}
                            colors={row.swatches[0].value ? [row.swatches[0].value] : []}
                          />
                        ) : (
                          <ColorItem
                            key={`${i}-${row.label}`}
                            title={row.label}
                            subtitle={`${row.swatches.length} ${row.swatches.length === 1 ? 'value' : 'values'}`}
                            colors={rowColors(row.swatches)}
                          />
                        ),
                      )}
                    </ColorPalette>
                    {unresolved.length > 0 && (
                      <div style={{ color: 'crimson' }}>
                        <p style={{ marginBottom: 4 }}>Unresolved — shown, never dropped:</p>
                        <ul style={{ marginTop: 0 }}>
                          {unresolved.map((s, ui) => (
                            <li key={`${ui}-${s.name}`}>
                              <code>{s.name}</code> — {s.unresolved}
                              {s.via ? <> (via <code>{s.via}</code>)</> : null}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          ))}

          {src.styles.length > 0 && (
            <div>
              <h2>Fill styles</h2>
              <p style={{ opacity: 0.7 }}>
                Styles are a separate source from variables — listed in the order the library
                declares them.
              </p>
              <ColorPalette>
                {src.styles.map((s) => (
                  <ColorItem
                    key={s.name}
                    title={s.name}
                    subtitle={s.unresolved ?? s.description}
                    colors={s.value ? [s.value] : []}
                  />
                ))}
              </ColorPalette>
            </div>
          )}
        </div>
      ))}
    </>
  );
}

const meta = {
  title: 'Foundations/Color',
  parameters: { ...pageParameters, docs: { page: ColorPage } },
} satisfies Meta;

export default meta;
export const Page: StoryObj = { render: () => <ColorPage /> };
