// Generated by `specs storybook` — rewritten on every publish. To take control
// of this page, copy it to content-overrides/overview/GettingStarted.stories.tsx
// and edit the copy; it then always wins and publish never touches it.
import * as React from 'react';
import type { Meta, StoryObj } from '@storybook/react';


const GettingStarted = () => (
  <div style={{ maxWidth: 640, font: '16px/1.6 system-ui, sans-serif' }}>
    <h1 style={{ marginTop: 0 }}>Getting started</h1>
    <p>
      This Storybook shows your design system as the workspace describes it — foundations read
      from your library&rsquo;s data, one entry per component with a tab per emitted platform,
      and the spec itself always one tab away.
    </p>
    <p>The loop after a library change:</p>
    <pre style={{ background: 'rgba(128,128,128,0.1)', padding: 12, borderRadius: 4 }}>
      {'specs fetch\nspecs generate\nspecs react\nspecs webcomponents\nspecs storybook       # refresh foundations, tabs, nav'}
    </pre>
    <p>
      Want your own version of a generated page? Copy it from <code>content/</code> to the same
      path under <code>content-overrides/</code> and edit the copy — it always wins, and no
      command ever writes there.
    </p>
  </div>
);

const meta = {
  title: 'Overview/Getting started',
  component: GettingStarted,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof GettingStarted>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Page: Story = { name: 'Getting started' };
