// Generated by `specs storybook` — rewritten on every publish. To take control
// of this page, copy it to content-overrides/foundations/Icons.stories.tsx and
// edit the copy; it then always wins and publish never touches it.
import * as React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { IconGallery, IconItem } from '@storybook/blocks';
// Via the workspace-anchored path (not './data/…') so a copy of this file in
// content-overrides/foundations/ keeps reading the published data.
import data from '../../content/foundations/data/icons.json';


const icons = data as {
  present: Array<{ name: string; referenced: boolean }>;
  missing: Array<{ name: string; referencedBy: string[] }>;
};

function IconsPage() {
  return (
    <>
      <h1>Icons</h1>

      {icons.missing.length > 0 && (
        <div
          style={{
            border: '1px solid crimson',
            borderRadius: 4,
            padding: '12px 16px',
            marginBottom: 24,
          }}
        >
          <p style={{ color: 'crimson', fontWeight: 600, marginTop: 0 }}>
            {icons.missing.length} referenced {icons.missing.length === 1 ? 'glyph is' : 'glyphs are'} missing
          </p>
          <p>
            A spec references these glyphs, but <code>specs fetch</code> wrote no file for them —
            which is the failure this page exists to make visible.
          </p>
          <ul style={{ marginBottom: 0 }}>
            {icons.missing.map((m) => (
              <li key={m.name}>
                <code>{m.name}.svg</code> — referenced by {m.referencedBy.join(', ')}
              </li>
            ))}
          </ul>
        </div>
      )}

      <p>
        Every glyph in the workspace, by the slug a spec references it with
        ({icons.present.length} fetched).
      </p>
      <IconGallery>
        {icons.present.map((g) => (
          <IconItem name={g.name} key={g.name}>
            <img src={`/assets/icons/${g.name}.svg`} alt="" style={{ width: 24, height: 24 }} />
          </IconItem>
        ))}
      </IconGallery>
    </>
  );
}

const meta = {
  title: 'Foundations/Icons',
  parameters: { docs: { page: IconsPage } },
} satisfies Meta;

export default meta;
export const Page: StoryObj = { render: () => <IconsPage /> };
