// Generated by `specs storybook` — rewritten on every publish. To take control
// of this page, copy it to content-overrides/foundations/Typography.stories.tsx
// and edit the copy; it then always wins and publish never touches it.
import * as React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Typeset } from '@storybook/blocks';
// Via the workspace-anchored path (not './data/…') so a copy of this file in
// content-overrides/foundations/ keeps reading the published data.
import data from '../../content/foundations/data/typography.json';

const ADDON_ID = 'specs/framework-tabs';
const pageParameters = {
  previewTabs: {
    canvas: { title: 'Page' },
    [`${ADDON_ID}/webcomponents`]: { hidden: true },
    [`${ADDON_ID}/specs`]: { hidden: true },
  },
};

interface TypeStyle {
  fontFamily: string;
  fontStyle?: string;
  fontWeight: number;
  fontSize: number;
  letterSpacing?: number;
  lineHeightPx?: number;
  lineHeightUnit?: string;
  textCase?: string;
  textDecoration?: string;
}
interface Entry {
  id: string;
  name: string;
  description: string;
  source: string;
  style: TypeStyle | null;
}

const styles = (data as { styles: Entry[] }).styles;

interface Group {
  name: string;
  styles: Array<Entry & { leaf: string }>;
}

/** Grouped by the first level of the name path, the same rule the colour page uses. */
function styleGroups(): Group[] {
  const groups = new Map<string, Group['styles']>();
  for (const s of styles) {
    const segments = s.name.split('/');
    const group = segments.length > 1 ? segments[0] : 'Ungrouped';
    const list = groups.get(group) ?? [];
    list.push({ ...s, leaf: segments[segments.length - 1] });
    groups.set(group, list);
  }
  return [...groups.entries()].map(([name, list]) => ({
    name,
    // Largest first: a specimen reads top-down from the display sizes.
    // Styles with no resolved properties sort last.
    styles: list.sort((a, b) => (b.style?.fontSize ?? -1) - (a.style?.fontSize ?? -1)),
  }));
}

function lineHeight(style: TypeStyle): string {
  if (style.lineHeightPx === undefined) return '—';
  const px = `${Math.round(style.lineHeightPx * 100) / 100}px`;
  return style.lineHeightUnit === 'INTRINSIC_%' ? `${px} (auto)` : px;
}

function families(): string[] {
  return [...new Set(styles.map((s) => s.style?.fontFamily).filter(Boolean) as string[])].sort();
}

function TypographyPage() {
  return (
    <>
      <h1>Typography</h1>
      <p>
        Every text style the file declares, with its full property set — letter spacing,
        line-height unit, case and decoration included — joined from the file&rsquo;s style map
        and its nodes when this page was published.
      </p>
      <p>Grouped by the first level of each name, the same rule the colour page uses.</p>
      <p>
        <strong>Families</strong> — {families().join(' · ')}
      </p>

      {styleGroups().map((group) => {
        const resolved = group.styles.filter((s) => s.style);
        return (
          <div key={group.name}>
            <h2>{group.name}</h2>

            {resolved.length > 0 && (
              <Typeset
                fontFamily={resolved[0].style!.fontFamily}
                // Unique sizes: Typeset keys its rows by size, so a duplicate
                // would both warn and collapse.
                fontSizes={[...new Set(resolved.map((s) => `${Math.round(s.style!.fontSize * 100) / 100}px`))]}
                fontWeight={resolved[0].style!.fontWeight}
                sampleText="The quick brown fox jumps over the lazy dog"
              />
            )}

            <table style={{ width: '100%', marginTop: 16 }}>
              <thead>
                <tr>
                  <th align="left">Style</th>
                  <th align="left">Weight</th>
                  <th align="left">Size</th>
                  <th align="left">Line height</th>
                  <th align="left">Letter spacing</th>
                  <th align="left">Case</th>
                  <th align="left">Decoration</th>
                </tr>
              </thead>
              <tbody>
                {group.styles.map((s) => (
                  <tr key={s.id + s.source}>
                    <td>
                      <code>{s.name}</code>
                      {s.description && (
                        <div style={{ opacity: 0.6, fontSize: 12 }}>{s.description}</div>
                      )}
                    </td>
                    {s.style ? (
                      <>
                        <td>
                          {s.style.fontStyle ?? ''} ({s.style.fontWeight})
                        </td>
                        <td>{Math.round(s.style.fontSize * 100) / 100}px</td>
                        <td>{lineHeight(s.style)}</td>
                        <td>{s.style.letterSpacing ? `${Math.round(s.style.letterSpacing * 100) / 100}px` : '—'}</td>
                        <td>{s.style.textCase ?? '—'}</td>
                        <td>{s.style.textDecoration ?? '—'}</td>
                      </>
                    ) : (
                      <td colSpan={6} style={{ color: 'crimson' }}>
                        Unresolved — no node in the file uses this style
                      </td>
                    )}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        );
      })}
    </>
  );
}

const meta = {
  title: 'Foundations/Typography',
  parameters: { ...pageParameters, docs: { page: TypographyPage } },
} satisfies Meta;

export default meta;
export const Page: StoryObj = { render: () => <TypographyPage /> };
