// Generated by `specs storybook` — rewritten on every publish. Placeholder:
// the Versions section holds its place until the versions index lands.
import * as React from 'react';
import type { Meta, StoryObj } from '@storybook/react';


const Versions = () => (
  <div style={{ maxWidth: 640, font: '16px/1.6 system-ui, sans-serif' }}>
    <h1 style={{ marginTop: 0 }}>Versions</h1>
    <p>
      Not built yet. This section will index the workspace versions `specs version cut` keeps
      under <code>versions/</code> — what changed, when, and at what grade.
    </p>
  </div>
);

const meta = {
  title: 'Versions/Overview',
  component: Versions,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Versions>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Page: Story = { name: 'Overview' };
