// Generated by `specs storybook` (visualtesting concern). Do not edit —
// regenerate with `specs storybook publish visualtesting`.
//
// Renders testing/visual/report/visual-report.json live (served at
// /baselines): re-running `specs testing visual diff` updates the page on
// reload, no Storybook restart needed.
import * as React from 'react';

type Pair = {
  nodeId: string;
  config: Record<string, string>;
  storyId: string | null;
  status: string;
  pass: boolean | null;
  dims?: { baseline: number[]; render: number[]; dw: number; dh: number };
  diffPct?: number;
  triptychPng?: string;
};

type Entry = {
  priority: { depth: number | null; leaf: boolean | null };
  summary: {
    passPct: number;
    variants: number;
    diffed: number;
    pass: number;
    fail: number;
    deferred: number;
    ignored?: number;
    meanDiffPct: number | null;
    maxDiffPct: number | null;
  };
  previous: { meanDiffPct: number | null } | null;
  pairs: Pair[];
};

type Report = {
  generatedAt: string;
  workspace: string;
  mode?: string;
  settings: { threshold: number; passPct: number; scale: number };
  ranking: { key: string; depth: number | null }[];
  compositionRanking?: { key: string; depth: number | null }[];
  components: Record<string, Entry>;
  compositions?: Record<string, Entry>;
};

const cell: React.CSSProperties = {
  padding: '4px 10px',
  borderBottom: '1px solid #ddd',
  textAlign: 'right',
  fontVariantNumeric: 'tabular-nums',
};
const cellLeft: React.CSSProperties = { ...cell, textAlign: 'left' };

function Bar({ pass, fail, rest }: { pass: number; fail: number; rest: number }) {
  const total = pass + fail + rest || 1;
  const seg = (n: number, color: string) => (
    <div style={{ width: `${(n / total) * 100}%`, background: color }} />
  );
  return (
    <div style={{ display: 'flex', height: 8, width: 120, borderRadius: 4, overflow: 'hidden', background: '#eee' }}>
      {seg(pass, '#2e9960')}
      {seg(fail, '#d64545')}
      {seg(rest, '#c9c9c9')}
    </div>
  );
}

type SortKey = 'ranking' | 'spec' | 'depth' | 'pass' | 'fail' | 'failPct' | 'passPct';
type Sort = { key: SortKey; dir: 'asc' | 'desc' };

const HEADERS: { label: string; sort?: SortKey }[] = [
  { label: 'spec', sort: 'spec' },
  { label: 'depth', sort: 'depth' },
  { label: 'ranking', sort: 'ranking' },
  { label: 'pass', sort: 'pass' },
  { label: 'fail', sort: 'fail' },
  { label: 'fail %', sort: 'failPct' },
  { label: 'diffed' },
  { label: 'deferred' },
  { label: 'ignored' },
  { label: 'mean %' },
  { label: 'max %' },
  { label: 'pass at', sort: 'passPct' },
  { label: 'Δ mean' },
];

function failPct(s: Entry['summary']): number | null {
  return s.variants ? (s.fail / s.variants) * 100 : null;
}

// Display-only namespace strip: keys in the JSON, story titles, and
// everywhere else keep the full spelling.
function displayName(key: string): string {
  const m = key.match(/^[a-z0-9]+(?=[A-Z])/);
  return m ? key.slice(m[0].length) : key;
}

function sortValue(key: SortKey, name: string, c: Entry): string | number {
  if (key === 'spec') return name;
  if (key === 'depth') return c.priority.depth ?? -1;
  if (key === 'failPct') return failPct(c.summary) ?? -1;
  return (c.summary as any)[key];
}

function Section({
  title,
  note,
  ranking,
  entries,
  defaultPassPct,
}: {
  title: string;
  note?: string;
  ranking: { key: string }[];
  entries: Record<string, Entry>;
  defaultPassPct: number;
}) {
  const [open, setOpen] = React.useState<string | null>(null);
  const [sort, setSort] = React.useState<Sort>({ key: 'fail', dir: 'desc' });

  const onSort = (key: SortKey) =>
    setSort((s) =>
      key === 'ranking'
        ? { key, dir: 'desc' }
        : s.key === key
          ? { key, dir: s.dir === 'asc' ? 'desc' : 'asc' }
          : { key, dir: key === 'spec' ? 'asc' : 'desc' },
    );

  const rows =
    sort.key === 'ranking'
      ? ranking
      : [...ranking].sort((a, b) => {
          const av = sortValue(sort.key, a.key, entries[a.key]);
          const bv = sortValue(sort.key, b.key, entries[b.key]);
          const cmp =
            typeof av === 'string' ? av.localeCompare(bv as string) : (av as number) - (bv as number);
          return sort.dir === 'asc' ? cmp : -cmp;
        });

  return (
    <div style={{ marginBottom: 32 }}>
      <h2 style={{ fontSize: 15, margin: '0 0 2px' }}>{title}</h2>
      {note ? <p style={{ color: '#666', margin: '0 0 10px' }}>{note}</p> : null}
      <table style={{ borderCollapse: 'collapse' }}>
        <thead>
          <tr>
            {HEADERS.map((h, i) => (
              <th
                key={i}
                onClick={h.sort ? () => onSort(h.sort!) : undefined}
                style={{
                  ...(i === 0 ? cellLeft : cell),
                  color: h.sort && sort.key === h.sort ? '#222' : '#666',
                  fontWeight: 500,
                  cursor: h.sort ? 'pointer' : undefined,
                  userSelect: 'none',
                  whiteSpace: 'nowrap',
                }}
              >
                {h.label}
                {h.sort && sort.key === h.sort && h.sort !== 'ranking'
                  ? sort.dir === 'asc'
                    ? ' ↑'
                    : ' ↓'
                  : ''}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map(({ key }) => {
            const c = entries[key];
            const s = c.summary;
            const delta =
              c.previous?.meanDiffPct != null && s.meanDiffPct != null
                ? (s.meanDiffPct - c.previous.meanDiffPct).toFixed(2)
                : '—';
            const worst =
              open === key
                ? c.pairs
                    .filter((p) => p.status === 'diffed' && p.pass === false && p.triptychPng)
                    .sort((a, b) => (b.diffPct ?? 0) - (a.diffPct ?? 0))
                    .slice(0, 6)
                : [];
            return (
              <React.Fragment key={key}>
                <tr
                  onClick={() => setOpen(open === key ? null : key)}
                  style={{ cursor: 'pointer', background: open === key ? '#f5f5f5' : undefined }}
                >
                  <td style={cellLeft}>
                    <b>{displayName(key)}</b>
                  </td>
                  <td style={cell}>{c.priority.depth ?? '?'}</td>
                  <td style={cell}>
                    <Bar pass={s.pass} fail={s.fail} rest={s.variants - s.pass - s.fail} />
                  </td>
                  <td style={{ ...cell, color: '#2e9960' }}>{s.pass}</td>
                  <td style={{ ...cell, color: s.fail ? '#d64545' : undefined }}>{s.fail}</td>
                  <td style={{ ...cell, color: s.fail ? '#d64545' : undefined }}>
                    {failPct(s) == null ? '—' : `${Math.round(failPct(s)!)}%`}
                  </td>
                  <td style={cell}>{s.diffed}</td>
                  <td style={cell}>{s.deferred || ''}</td>
                  <td
                    style={cell}
                    title="Deliberately excluded via visual-ignore — a reviewed judgment, kept visible rather than dropped from the counts"
                  >
                    {s.ignored || ''}
                  </td>
                  <td style={cell}>{s.meanDiffPct ?? '—'}</td>
                  <td style={cell}>{s.maxDiffPct ?? '—'}</td>
                  <td
                    style={{ ...cell, color: s.passPct !== defaultPassPct ? '#b26a00' : '#999' }}
                    title={
                      s.passPct !== defaultPassPct
                        ? `Held to its own bar, not the workspace default of ${defaultPassPct}% — see visual-ignore.yaml`
                        : 'The workspace default'
                    }
                  >
                    {s.passPct}%
                  </td>
                  <td style={cell}>{delta}</td>
                </tr>
                {open === key && (
                  <tr>
                    <td colSpan={HEADERS.length} style={{ ...cellLeft, background: '#fafafa', padding: 12 }}>
                      {worst.length === 0 ? (
                        <span style={{ color: '#666' }}>
                          No failing diffed pairs — failures here are coverage
                          (no-baseline/deferred) rows, or everything passes.
                        </span>
                      ) : (
                        worst.map((p) => (
                          <div key={p.nodeId} style={{ marginBottom: 16 }}>
                            <div style={{ color: '#666', marginBottom: 4 }}>
                              {p.diffPct}% · dw {p.dims?.dw} dh {p.dims?.dh} ·{' '}
                              {Object.entries(p.config)
                                .map(([k, v]) => `${k}=${v}`)
                                .join(', ') || 'default'}
                            </div>
                            <img
                              src={`/baselines/${p.triptychPng}`}
                              alt={`${key} ${p.nodeId} baseline vs render vs diff`}
                              style={{ maxWidth: '100%', border: '1px solid #ddd', borderRadius: 4 }}
                            />
                          </div>
                        ))
                      )}
                    </td>
                  </tr>
                )}
              </React.Fragment>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

function VisualReport() {
  const [report, setReport] = React.useState<Report | null>(null);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    fetch('/baselines/report/visual-report.json')
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`${r.status}`))))
      .then(setReport)
      .catch(() =>
        setError(
          'No report found at /baselines/report/visual-report.json — run `specs testing visual diff`, then reload.',
        ),
      );
  }, []);

  if (error) return <p style={{ font: '14px system-ui', maxWidth: 560 }}>{error}</p>;
  if (!report) return <p style={{ font: '14px system-ui' }}>Loading…</p>;

  const totals = Object.values(report.components).reduce(
    (t, c) => ({
      pass: t.pass + c.summary.pass,
      fail: t.fail + c.summary.fail,
      variants: t.variants + c.summary.variants,
      diffed: t.diffed + c.summary.diffed,
    }),
    { pass: 0, fail: 0, variants: 0, diffed: 0 },
  );

  return (
    <div style={{ font: '13px system-ui', padding: 16, maxWidth: 1100 }}>
      <h1 style={{ fontSize: 18, margin: '0 0 4px' }}>Visual report</h1>
      <p style={{ color: '#666', margin: '0 0 16px' }}>
        {new Date(report.generatedAt).toLocaleString()} · mode {report.mode ?? 'figma'} · scale{' '}
        {report.settings.scale} · default passPct {report.settings.passPct}% · {totals.diffed}/
        {totals.variants} variants diffed ·{' '}
        <b style={{ color: '#2e9960' }}>{totals.pass} pass</b> ·{' '}
        <b style={{ color: '#d64545' }}>{totals.fail} fail</b>
      </p>
      <Section
        title="Components"
        ranking={report.ranking}
        entries={report.components}
        defaultPassPct={report.settings.passPct}
      />
      {report.compositionRanking && report.compositionRanking.length > 0 && report.compositions ? (
        <Section
          title="Compositions (informational)"
          note="These results don't fail a run. A page is built from components, so when a component is off, every page using it looks off too — fix the components above first."
          ranking={report.compositionRanking}
          entries={report.compositions}
          defaultPassPct={report.settings.passPct}
        />
      ) : null}
      <p style={{ color: '#999', margin: '8px 0 24px' }}>
        Click a column to sort; “ranking” restores the default order. Click a row to expand its
        worst failures inline.
      </p>
    </div>
  );
}

export default {
  title: 'Testing/Visual Differences',
  parameters: {
    previewTabs: {
      canvas: { title: 'Page' },
      'specs-spike/framework-tabs/webcomponents': { hidden: true },
      'specs-spike/framework-tabs/specs': { hidden: true },
    },
    layout: 'fullscreen',
    options: { showPanel: false },
  },
};

export const Status = { render: () => <VisualReport /> };
