import fs from 'fs-extra';
import path from 'path';
import yaml from 'yaml';
import type { Transformer, TransformerContext } from '../Types/Transformer.js';
import { CONCEPT_TABLE, buildOmittedProps, type ProcessingStates } from './states.js';
import { isTokenRef } from './css/values.js';

type Rec = Record<string, unknown>;

/**
 * Emits `component.md` — a deterministic, single-file markdown reference for a
 * component, projected verbatim from the spec (api.yaml + variants.yaml).
 * No inference: every value is a mechanical restatement of spec data.
 */
export class ComponentMdTransformer implements Transformer {
  readonly name = 'component-md';

  async run(apiYaml: Rec, context: TransformerContext): Promise<void> {
    const { outputDir, componentKey } = context;

    const variantsYaml = await readSiblingYaml(outputDir, 'variants.yaml');
    const examplesYaml = await readSiblingYaml(outputDir, 'examples.yaml');

    const spec = mergeConcerns(apiYaml, variantsYaml, examplesYaml);
    const lines = buildComponentMd(spec, componentKey, context.processingStates);
    await fs.writeFile(path.join(outputDir, 'component.md'), lines.join('\n') + '\n', 'utf-8');

    // Subcomponents — each gets its own subfolder/component.md
    const apiSubs = (apiYaml.subcomponents ?? {}) as Rec;
    const variantSubs = ((variantsYaml?.subcomponents ?? {})) as Rec;
    for (const [subKey, subApiRaw] of Object.entries(apiSubs)) {
      const subApi = subApiRaw as Rec;
      const subVariants = (variantSubs[subKey] ?? {}) as Rec;
      const subSpec = mergeConcerns(subApi, subVariants, undefined);
      const subLines = buildComponentMd(subSpec, subKey, context.processingStates, componentKey);
      const subDir = path.join(outputDir, subKey);
      await fs.ensureDir(subDir);
      await fs.writeFile(path.join(subDir, 'component.md'), subLines.join('\n') + '\n', 'utf-8');
    }
  }
}

async function readSiblingYaml(dir: string, name: string): Promise<Rec | undefined> {
  const p = path.join(dir, name);
  if (!fs.existsSync(p)) return undefined;
  const raw = await fs.readFile(p, 'utf-8');
  return yaml.parse(raw) as Rec;
}

/** Combine api/variants/examples concerns into one spec-shaped record. api.yaml may already be monolithic. */
function mergeConcerns(api: Rec, variants: Rec | undefined, examples: Rec | undefined): Rec {
  return {
    ...api,
    default: variants?.default ?? api.default,
    variants: variants?.variants ?? api.variants ?? [],
    invalidVariantCombinations: variants?.invalidVariantCombinations ?? api.invalidVariantCombinations,
    slotContentExamples: examples?.slotContentExamples ?? api.slotContentExamples,
    instanceExamples: examples?.instanceExamples ?? api.instanceExamples,
  };
}

// ---------------------------------------------------------------------------
// Document assembly
// ---------------------------------------------------------------------------

function buildComponentMd(
  spec: Rec,
  componentKey: string,
  processingStates: ProcessingStates | undefined,
  parentKey?: string,
): string[] {
  const props = (spec.props ?? {}) as Rec;
  const anatomy = (spec.anatomy ?? {}) as Rec;
  const dflt = (spec.default ?? {}) as Rec;
  const variants = (spec.variants ?? []) as Rec[];
  const subcomponents = (spec.subcomponents ?? {}) as Rec;
  const title = (spec.title as string) ?? componentKey;

  const lines: string[] = [];
  lines.push(`# ${title}`);
  lines.push('');
  lines.push(
    '> Generated by `specs transform component-md` — a deterministic projection of the component spec.',
    '> Every value is verbatim from the spec; regenerate rather than edit.',
    `> Canonical data: \`api.yaml\` · \`variants.yaml\`.${parentKey ? ` Subcomponent of \`${parentKey}\`.` : ''}`,
    '>',
    '> **How to read.** To resolve a configuration: start from Element styles (default), then apply every',
    '> variant delta whose configuration matches, in the order listed — later values win per property.',
    '> `unset` removes the default value. `← prop` marks a value bound to a prop;',
    '> `` if `prop` op → a : b `` marks a conditional value. Tokens render as `` `path` (type, raw value) ``.',
    '> Shadows render as `[inset] offset-x offset-y blur spread color`.',
  );

  section(lines, 'Overview', buildOverview(title, props, anatomy, dflt, variants, subcomponents, spec));
  section(lines, 'Props', buildProps(props, anatomy, dflt, variants, processingStates));
  section(lines, 'Bindings', buildBindings(anatomy, dflt, variants, props), true);
  section(lines, 'States', buildStates(props, processingStates), true);
  section(lines, 'Anatomy', buildAnatomy(anatomy, dflt, variants, props));
  section(lines, 'Layout', buildLayout(dflt, variants));
  section(lines, 'Element styles (default)', buildDefaultStyles(dflt));
  section(lines, 'Typography', buildTypography(anatomy, dflt, variants), true);
  section(lines, 'Color', buildColor(dflt, variants), true);
  section(lines, 'Variant deltas', buildVariantDeltas(dflt, variants), true);
  section(lines, 'Invalid combinations', buildInvalidCombinations(spec, props, variants), true);
  section(lines, 'Subcomponents', buildSubcomponents(subcomponents), true);
  section(lines, 'Examples', buildExamples(spec, props), true);
  section(lines, 'Provenance', buildProvenance(spec));

  return lines;
}

/** Append a `## title` section. When optional, omit the section entirely if body is empty. */
function section(lines: string[], title: string, body: string[], optional = false): void {
  if (optional && body.length === 0) return;
  lines.push('', `## ${title}`, '');
  if (body.length === 0) {
    lines.push('_None._');
  } else {
    lines.push(...body);
  }
}

// ---------------------------------------------------------------------------
// Sections
// ---------------------------------------------------------------------------

function buildOverview(
  title: string,
  props: Rec,
  anatomy: Rec,
  dflt: Rec,
  variants: Rec[],
  subcomponents: Rec,
  spec: Rec,
): string[] {
  const counts: string[] = [];
  counts.push(`${plural(Object.keys(props).length, 'prop')}`);
  counts.push(`${plural(Object.keys(anatomy).length, 'anatomy element')}`);
  counts.push(`${plural(variants.length, 'variant delta')}`);
  if (Object.keys(subcomponents).length > 0) {
    counts.push(`${plural(Object.keys(subcomponents).length, 'subcomponent')}`);
  }
  const body = [`${title} defines ${counts.join(', ')}.`];

  const axes = variantAxes(props, variants);
  if (axes.length > 0) {
    // Axes never referenced by any delta configuration or invalid combination are flagged,
    // so silence reads as "no recorded impact" instead of missing data.
    const referencedKeys = new Set<string>();
    for (const v of variants) {
      for (const key of Object.keys((v.configuration ?? {}) as Rec)) referencedKeys.add(key);
    }
    for (const combo of ((spec.invalidVariantCombinations ?? []) as Rec[])) {
      for (const key of Object.keys(combo)) referencedKeys.add(key);
    }

    body.push('');
    const parts = axes.map(([key, prop]) => {
      const p = prop as Rec;
      const inert = !referencedKeys.has(key) ? ' — no style impact recorded' : '';
      if (p.type === 'boolean') return `\`${key}\` (boolean; default \`${p.default}\`${inert})`;
      const values = ((p.enum ?? []) as unknown[]).map(v => String(v)).join(' · ');
      return `\`${key}\` (${values}; default \`${p.default}\`${inert})`;
    });
    body.push(`**Variant axes.** ${parts.join(' — ')}`);

    // Section manifest with defined counts, so a reader can budget the file from the top.
    const layoutTrees = countDistinctLayouts(dflt, variants);
    const invalidCount = ((spec.invalidVariantCombinations ?? []) as Rec[]).length;
    const space = configurationSpace(axes);
    const manifest: string[] = [`${variants.length} variant deltas`, `${plural(layoutTrees, 'layout tree')}`];
    if (invalidCount > 0) manifest.push(`${invalidCount} invalid combinations`);
    if (space > 0) manifest.push(`configuration space ${space}`);
    body.push('');
    body.push(`**Contents.** ${manifest.join(' · ')}`);
  }
  return body;
}

/** Product of axis cardinalities (enum length; booleans count 2). */
function configurationSpace(axes: Array<[string, Rec]>): number {
  let product = 1;
  for (const [, p] of axes) {
    product *= p.type === 'boolean' ? 2 : Array.isArray(p.enum) ? (p.enum as unknown[]).length : 1;
  }
  return axes.length > 0 ? product : 0;
}

function countDistinctLayouts(dflt: Rec, variants: Rec[]): number {
  const shapes = new Set<string>([JSON.stringify(dflt.layout ?? [])]);
  for (const v of variants) {
    if (v.layout) shapes.add(JSON.stringify(v.layout));
  }
  return shapes.size;
}

/** Axes = enum props, plus booleans that appear in any variant configuration or carry a Figma VARIANT extension. */
function variantAxes(props: Rec, variants: Rec[]): Array<[string, Rec]> {
  const configuredKeys = new Set<string>();
  for (const v of variants) {
    for (const key of Object.keys((v.configuration ?? {}) as Rec)) configuredKeys.add(key);
  }
  return Object.entries(props)
    .map(([k, p]) => [k, p as Rec] as [string, Rec])
    .filter(([k, p]) => {
      if (p.type === 'string' && Array.isArray(p.enum)) return true;
      if (p.type === 'boolean') {
        if (configuredKeys.has(k)) return true;
        const ext = ((p.$extensions as Rec)?.['com.figma'] as Rec)?.type;
        return ext === 'VARIANT';
      }
      return false;
    });
}

function buildProps(
  props: Rec,
  anatomy: Rec,
  dflt: Rec,
  variants: Rec[],
  processingStates: ProcessingStates | undefined,
): string[] {
  const entries = Object.entries(props);
  if (entries.length === 0) return ['_No props._'];

  const omitted = buildOmittedProps(processingStates ?? {});
  const bindingsByProp = collectBindings(anatomy, dflt, variants, props);

  const rows: string[][] = [];
  for (const [key, raw] of entries) {
    const p = raw as Rec;
    const type = p.type as string;
    const nullable = p.nullable === true || p.default === null;
    const typeLabel =
      type === 'string' && Array.isArray(p.enum) ? 'enum' : nullable && type === 'string' ? 'string \\| null' : type;
    const dfltLabel = 'default' in p ? code(formatScalar(p.default)) : '—';
    const values = Array.isArray(p.enum) ? (p.enum as unknown[]).map(v => code(String(v))).join(' ') : '—';

    const notes: string[] = [];
    if (type === 'slot') {
      notes.push(slotConstraintNote(p));
    }
    const sourceKind = (((p.$extensions as Rec)?.['com.figma'] as Rec)?.source as Rec | undefined)?.kind;
    if (sourceKind === 'codeOnlyProp') notes.push('code-only prop — not rendered in Figma');
    if (omitted.has(key)) notes.push('browser-driven state — omitted from `contract.ts`');
    const bound = bindingsByProp.get(key);
    if (bound) notes.push(bound.join('; '));
    if (Array.isArray(p.examples) && p.examples.length > 0) {
      notes.push(`e.g. ${code(String((p.examples as unknown[])[0]))}`);
    }

    rows.push([code(key), typeLabel, dfltLabel, values, notes.join('; ') || '—']);
  }
  return table(['Prop', 'Type', 'Default', 'Values', 'Notes'], rows);
}

/** `slot` plus any child constraints the spec declares (minChildren / maxChildren / anyOf). */
function slotConstraintNote(p: Rec): string {
  const constraints: string[] = [];
  if (typeof p.minChildren === 'number') constraints.push(`min ${p.minChildren}`);
  if (typeof p.maxChildren === 'number') constraints.push(`max ${p.maxChildren}`);
  if (Array.isArray(p.anyOf)) constraints.push(`accepts ${(p.anyOf as unknown[]).map(x => code(String(x))).join(' ')}`);
  return constraints.length > 0 ? `slot (${constraints.join(', ')})` : 'slot';
}

/** Walk element properties for `$binding` refs (direct or inside conditionals); index prose by prop name. */
function collectBindings(anatomy: Rec, dflt: Rec, variants: Rec[], props: Rec): Map<string, string[]> {
  const byProp = new Map<string, string[]>();
  for (const { element, property, propName, condition, scope } of findBindings(anatomy, dflt, variants)) {
    if (!(propName in props)) continue;
    const list = byProp.get(propName) ?? [];
    const when = scope ? ` (when ${scope})` : '';
    list.push(condition ? `${condition} → \`${element}.${property}\`${when}` : `bound to \`${element}.${property}\`${when}`);
    byProp.set(propName, list);
  }
  return byProp;
}

interface FoundBinding {
  element: string;
  property: string;
  propName: string;
  condition?: string;
  /** Formatted configuration when the binding appears only in a variant, undefined for default-scope. */
  scope?: string;
}

function findBindings(anatomy: Rec, dflt: Rec, variants: Rec[]): FoundBinding[] {
  const found: FoundBinding[] = [];
  const seen = new Set<string>();

  const scan = (element: string, elData: Rec, scope?: string) => {
    const targets: Rec = {
      ...(elData.styles as Rec),
      instanceOf: elData.instanceOf,
      content: elData.content,
      children: elData.children,
      visible: (elData.styles as Rec)?.visible ?? elData.visible,
    };
    for (const [property, value] of Object.entries(targets)) {
      if (value === null || value === undefined) continue;
      const binding = extractBinding(value);
      if (!binding) continue;
      const key = `${element}.${property}.${binding.propName}`;
      if (seen.has(key)) continue;
      seen.add(key);
      found.push({ element, property, propName: binding.propName, condition: binding.condition, scope });
    }
  };

  // Default scope first so it wins the dedup over variant-scoped repeats.
  for (const [el, raw] of Object.entries((dflt.elements ?? {}) as Rec)) scan(el, raw as Rec);
  for (const [el, raw] of Object.entries(anatomy)) scan(el, raw as Rec);
  for (const v of variants) {
    const scope = formatConfiguration((v.configuration ?? {}) as Rec);
    for (const [el, raw] of Object.entries((v.elements ?? {}) as Rec)) scan(el, raw as Rec, scope);
  }
  return found;
}

function extractBinding(value: unknown): { propName: string; condition?: string; outcome?: string } | null {
  if (typeof value !== 'object' || value === null) return null;
  const v = value as Rec;
  if (typeof v.$binding === 'string') {
    return { propName: bindingPointerToProp(v.$binding) };
  }
  if (typeof v.if === 'object' && v.if !== null) {
    const ifBlock = v.if as Rec;
    const cond = (ifBlock.condition ?? {}) as Rec;
    const args = (cond.args ?? {}) as Rec;
    const binding = args.value as Rec | undefined;
    if (binding && typeof binding.$binding === 'string') {
      const propName = bindingPointerToProp(binding.$binding);
      const op = cond.operation as string;
      const compareTo = 'compareTo' in args ? ` ${formatScalar(args.compareTo)}` : '';
      const outcome =
        'then' in ifBlock || 'else' in ifBlock
          ? `→ ${formatScalar(ifBlock.then)} : ${formatScalar(ifBlock.else)}`
          : undefined;
      return { propName, condition: `\`${propName}\` ${op}${compareTo}`, outcome };
    }
  }
  return null;
}

function bindingPointerToProp(pointer: string): string {
  return pointer.replace(/^#\/props\//, '');
}

function buildBindings(anatomy: Rec, dflt: Rec, variants: Rec[], props: Rec): string[] {
  const found = findBindings(anatomy, dflt, variants).filter(b => b.propName in props);
  if (found.length === 0) return [];
  const rows = found.map(b => [
    code(b.element),
    code(b.property),
    code(b.propName),
    b.condition ?? 'direct',
    b.scope ?? 'default',
  ]);
  return table(['Element', 'Property', 'Bound prop', 'Condition', 'When'], rows);
}

function buildStates(props: Rec, processingStates: ProcessingStates | undefined): string[] {
  if (!processingStates) return [];

  interface StateRow {
    concept: string;
    prop: string;
    value: string;
    entry: { contract?: 'omit' | 'keep' };
  }
  const valid: StateRow[] = [];
  const matchedByProp = new Map<string, Set<string>>();

  for (const [concept, entry] of Object.entries(processingStates)) {
    const prop = props[entry.prop] as Rec | undefined;
    if (!prop) continue;
    const candidates = [entry.value ?? 'true', concept].map(s => String(s).toLowerCase());

    if (Array.isArray(prop.enum)) {
      // Only surface concepts whose activating value can actually match an enum value;
      // display the enum's own casing.
      const match = (prop.enum as unknown[]).find(v => candidates.includes(String(v).toLowerCase()));
      if (match === undefined) continue;
      valid.push({ concept, prop: entry.prop, value: String(match), entry });
      const set = matchedByProp.get(entry.prop) ?? new Set<string>();
      set.add(String(match));
      matchedByProp.set(entry.prop, set);
    } else if (prop.type === 'boolean') {
      // Boolean props can only be activated by true/false.
      const v = String(entry.value ?? 'true').toLowerCase();
      if (v !== 'true' && v !== 'false') continue;
      valid.push({ concept, prop: entry.prop, value: v, entry });
    } else {
      valid.push({ concept, prop: entry.prop, value: String(entry.value ?? 'true'), entry });
    }
  }
  if (valid.length === 0) return [];

  const rows = valid.map(({ concept, prop, value, entry }) => {
    const def = CONCEPT_TABLE[concept];
    const contract = entry.contract ?? def?.contract ?? 'keep';
    return [
      code(concept),
      code(prop),
      code(value),
      def ? code(def.selector) : '—',
      contract === 'omit' ? 'omitted — browser-driven' : 'included — consumer-controlled',
    ];
  });

  // Enum values on classified props with no concept mapping and not the base default —
  // surfaced so "unclassified" is distinguishable from "no such state".
  for (const [propKey, matched] of matchedByProp) {
    const prop = props[propKey] as Rec;
    if (!Array.isArray(prop.enum)) continue;
    for (const enumValue of prop.enum as unknown[]) {
      const s = String(enumValue);
      if (matched.has(s)) continue;
      if (String(prop.default) === s) continue; // base state — covered by defaults
      rows.push(['—', code(propKey), code(s), '—', 'unclassified — no concept mapping']);
    }
  }

  return [
    'Semantic state classification from `config.processing.states`. Browser-driven states are fired by the platform, not set by consumers; non-web platforms map the concept, not the selector.',
    '',
    ...table(['State', 'Prop', 'Value', 'Web selector(s)', 'Contract'], rows),
  ];
}

function buildAnatomy(anatomy: Rec, dflt: Rec, variants: Rec[], props: Rec): string[] {
  const entries = Object.entries(anatomy);
  if (entries.length === 0) return ['_No anatomy._'];
  const defaultLayoutKeys = new Set(flattenLayout((dflt.layout ?? []) as unknown[]));

  // Element-presence pivot: which variant layouts contain each element.
  const variantLayouts = variants.filter(v => Array.isArray(v.layout));
  const presenceFor = (key: string): string => {
    const inDefault = defaultLayoutKeys.has(key);
    if (variantLayouts.length === 0) return inDefault ? 'default' : '—';
    const inConfigs = variantLayouts.filter(v => flattenLayout(v.layout as unknown[]).includes(key));
    const inAll = inConfigs.length === variantLayouts.length;
    if (inDefault && inAll) return 'always';
    if (inDefault && inConfigs.length === 0) return 'default only';
    if (!inDefault && inAll) return 'all variant layouts (not default)';
    const configs = inConfigs.map(v => formatConfiguration((v.configuration ?? {}) as Rec));
    const list = configs.length <= 4 ? configs.join(' · ') : `${plural(configs.length, 'variant layout')}`;
    return inDefault ? `default · ${list}` : list;
  };

  const rows = entries.map(([key, raw]) => {
    const el = raw as Rec;
    const notes: string[] = [];
    if (el.detectedIn) notes.push(`detected in ${normalizeDetectedIn(String(el.detectedIn), props)}`);
    return [
      code(key),
      String(el.type ?? '—'),
      el.instanceOf ? formatValue(el.instanceOf) : '—',
      presenceFor(key),
      notes.join('; ') || '—',
    ];
  });
  return table(['Element', 'Type', 'Instance of', 'Presence', 'Notes'], rows);
}

/**
 * Translate a raw Figma configuration string (`Appearance=Solid, Size=Small`) into
 * prop vocabulary (`appearance: Solid, size: Small`). Keys match case-insensitively
 * ignoring non-alphanumerics; boolean values lowercase; unmatched segments stay verbatim.
 */
function normalizeDetectedIn(detectedIn: string, props: Rec): string {
  const canonical = new Map<string, string>();
  for (const key of Object.keys(props)) {
    canonical.set(key.toLowerCase().replace(/[^a-z0-9]/g, ''), key);
  }
  const parts = detectedIn.split(', ').map(segment => {
    const eq = segment.indexOf('=');
    if (eq === -1) return segment;
    const rawKey = segment.slice(0, eq);
    const rawValue = segment.slice(eq + 1);
    const propKey = canonical.get(rawKey.toLowerCase().replace(/[^a-z0-9]/g, ''));
    if (!propKey) return segment;
    return `${propKey}: ${normalizePropValue(rawValue, props[propKey] as Rec)}`;
  });
  return code(parts.join(', '));
}

/** Normalize a raw variant value to the prop's declared casing (booleans lowercase, enums by case-insensitive match). */
function normalizePropValue(rawValue: string, prop: Rec | undefined): string {
  if (!prop) return rawValue;
  if (prop.type === 'boolean') return rawValue.toLowerCase();
  if (Array.isArray(prop.enum)) {
    const match = (prop.enum as unknown[]).find(v => String(v).toLowerCase() === rawValue.toLowerCase());
    if (match !== undefined) return String(match);
  }
  return rawValue;
}

function buildLayout(dflt: Rec, variants: Rec[]): string[] {
  const body: string[] = [];
  const defaultLayout = (dflt.layout ?? []) as unknown[];
  const defaultKeys = new Set(flattenLayout(defaultLayout));
  body.push('### Default', '');
  body.push(...renderLayoutTree(defaultLayout));

  // Group variant layouts by identical shape so repeated trees render once.
  const groups = new Map<string, { configs: string[]; layout: unknown[] }>();
  for (const v of variants) {
    if (!v.layout) continue;
    const key = JSON.stringify(v.layout);
    const g = groups.get(key) ?? { configs: [], layout: v.layout as unknown[] };
    g.configs.push(formatConfiguration((v.configuration ?? {}) as Rec));
    groups.set(key, g);
  }

  const changed = [...groups.values()].filter(g => JSON.stringify(g.layout) !== JSON.stringify(defaultLayout));
  if (changed.length > 0) {
    body.push('', '### Variant layout changes', '');
    for (const g of changed) {
      body.push(`**${g.configs.join('** · **')}**`, '');
      const diff = layoutDiff(defaultKeys, new Set(flattenLayout(g.layout)));
      if (diff) body.push(`_vs default: ${diff}_`, '');
      body.push(...renderLayoutTree(g.layout), '');
    }
    while (body[body.length - 1] === '') body.pop();
  }
  return body;
}

/** Element-set diff between two layouts: `+ added − removed`. Empty string when sets match (pure restructure). */
function layoutDiff(defaultKeys: Set<string>, keys: Set<string>): string {
  const added = [...keys].filter(k => !defaultKeys.has(k));
  const removed = [...defaultKeys].filter(k => !keys.has(k));
  const parts: string[] = [];
  if (added.length > 0) parts.push(`+ ${added.join(', ')}`);
  if (removed.length > 0) parts.push(`− ${removed.join(', ')}`);
  return parts.join(' · ');
}

function renderLayoutTree(layout: unknown[], depth = 0): string[] {
  const lines: string[] = [];
  for (const node of layout) {
    if (typeof node === 'string') {
      lines.push(`${'  '.repeat(depth)}- ${node}`);
    } else if (typeof node === 'object' && node !== null) {
      for (const [key, children] of Object.entries(node as Rec)) {
        lines.push(`${'  '.repeat(depth)}- ${key}`);
        if (Array.isArray(children)) lines.push(...renderLayoutTree(children, depth + 1));
      }
    }
  }
  return lines;
}

function flattenLayout(layout: unknown[]): string[] {
  const keys: string[] = [];
  for (const node of layout) {
    if (typeof node === 'string') keys.push(node);
    else if (typeof node === 'object' && node !== null) {
      for (const [key, children] of Object.entries(node as Rec)) {
        keys.push(key);
        if (Array.isArray(children)) keys.push(...flattenLayout(children));
      }
    }
  }
  return keys;
}

/** Rows for one element's non-style facts: content and (in deltas) instanceOf. */
function elementFactRows(el: Rec, includeInstanceOf: boolean): string[][] {
  const rows: string[][] = [];
  if (includeInstanceOf && el.instanceOf !== undefined) {
    rows.push([code('instanceOf'), formatValue(el.instanceOf)]);
  }
  if (el.content !== undefined) {
    rows.push([code('content'), formatValue(el.content)]);
  }
  return rows;
}

function buildDefaultStyles(dflt: Rec): string[] {
  const elements = (dflt.elements ?? {}) as Rec;
  const body: string[] = [];
  for (const [elKey, raw] of Object.entries(elements)) {
    const el = raw as Rec;
    const rows: string[][] = elementFactRows(el, false);
    for (const [prop, value] of flattenStyles((el.styles ?? {}) as Rec)) {
      rows.push([code(prop), formatValue(value)]);
    }
    for (const [prop, value] of Object.entries((el.propConfigurations ?? {}) as Rec)) {
      rows.push([code(`propConfigurations.${prop}`), formatValue(value)]);
    }
    if (rows.length === 0) continue;
    const suffix = el.instanceOf ? ` — instance of ${formatValue(el.instanceOf)}` : '';
    body.push(`### ${elKey}${suffix}`, '');
    body.push(...table(['Property', 'Value'], rows), '');
  }
  while (body[body.length - 1] === '') body.pop();
  return body.length > 0 ? body : ['_No default element styles._'];
}

const TYPOGRAPHY_PROPS = new Set(['typography', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'letterSpacing', 'textCase', 'textDecoration']);

function buildTypography(anatomy: Rec, dflt: Rec, variants: Rec[]): string[] {
  const rows: string[][] = [];
  const elements = (dflt.elements ?? {}) as Rec;
  for (const [elKey, raw] of Object.entries(elements)) {
    const styles = ((raw as Rec).styles ?? {}) as Rec;
    for (const [prop, value] of Object.entries(styles)) {
      if (!TYPOGRAPHY_PROPS.has(prop)) continue;
      const overrides = variantOverridesFor(variants, elKey, prop);
      rows.push([code(elKey), code(prop), formatValue(value), overrides.length > 0 ? overrides.join('; ') : '—']);
    }
  }
  if (rows.length === 0) return [];
  return table(['Element', 'Property', 'Default', 'Variant overrides'], rows);
}

function buildColor(dflt: Rec, variants: Rec[]): string[] {
  // Collect every (element, property) pair carrying a color-typed value anywhere.
  const pairs = new Map<string, { element: string; prop: string }>();
  const collect = (elements: Rec) => {
    for (const [elKey, raw] of Object.entries(elements)) {
      for (const [prop, value] of Object.entries(((raw as Rec).styles ?? {}) as Rec)) {
        if (isColorValue(value, prop)) pairs.set(`${elKey} ${prop}`, { element: elKey, prop });
      }
    }
  };
  collect((dflt.elements ?? {}) as Rec);
  for (const v of variants) collect((v.elements ?? {}) as Rec);

  if (pairs.size === 0) return [];

  const rows: string[][] = [];
  const defaultElements = (dflt.elements ?? {}) as Rec;
  const sorted = [...pairs.values()].sort((a, b) =>
    a.element === b.element ? a.prop.localeCompare(b.prop) : a.element.localeCompare(b.element),
  );
  for (const { element, prop } of sorted) {
    const defaultValue = (((defaultElements[element] as Rec)?.styles ?? {}) as Rec)[prop];
    const overrides = variantOverridesFor(variants, element, prop);
    rows.push([
      code(element),
      code(prop),
      defaultValue !== undefined ? formatValue(defaultValue) : '—',
      overrides.length > 0 ? overrides.join('; ') : '—',
    ]);
  }
  return table(['Element', 'Property', 'Default', 'Variant overrides'], rows);
}

/** `configuration → value` strings for every variant that overrides element.prop. */
function variantOverridesFor(variants: Rec[], element: string, prop: string): string[] {
  const out: string[] = [];
  for (const v of variants) {
    const styles = ((((v.elements ?? {}) as Rec)[element] as Rec)?.styles ?? {}) as Rec;
    if (prop in styles) {
      out.push(`${formatConfiguration((v.configuration ?? {}) as Rec)} → ${formatValue(styles[prop])}`);
    }
  }
  return out;
}

function buildVariantDeltas(dflt: Rec, variants: Rec[]): string[] {
  if (variants.length === 0) return [];
  const body: string[] = [];
  const defaultKeys = new Set(flattenLayout((dflt.layout ?? []) as unknown[]));

  let index = 0;
  for (const v of variants) {
    index++;
    const rows: string[][] = [];
    const hoisted: string[] = [];
    for (const [elKey, raw] of Object.entries((v.elements ?? {}) as Rec)) {
      const el = raw as Rec;
      for (const [prop, value] of elementFactRows(el, true)) {
        rows.push([code(elKey), prop, value]);
      }
      for (const [prop, value] of flattenStyles((el.styles ?? {}) as Rec)) {
        if (isColorValue(value, prop)) {
          hoisted.push(`${code(`${elKey}.${prop}`)}`); // color deltas live in the Color section
          continue;
        }
        rows.push([code(elKey), code(prop), formatValue(value)]);
      }
      for (const [prop, value] of Object.entries((el.propConfigurations ?? {}) as Rec)) {
        rows.push([code(elKey), code(`propConfigurations.${prop}`), formatValue(value)]);
      }
    }
    const hasLayoutChange = Boolean(v.layout);
    if (rows.length === 0 && !hasLayoutChange && hoisted.length === 0) continue;

    body.push(`### ${index}. ${formatConfiguration((v.configuration ?? {}) as Rec)}`, '');
    if (hasLayoutChange) {
      const diff = layoutDiff(defaultKeys, new Set(flattenLayout(v.layout as unknown[])));
      body.push(`_Layout${diff ? `: ${diff}` : ' restructured'} — see [Layout](#layout)._`, '');
    }
    if (hoisted.length > 0) {
      body.push(`_Color: ${hoisted.join(', ')} — see [Color](#color)._`, '');
    }
    if (rows.length > 0) body.push(...table(['Element', 'Property', 'Value'], rows), '');
  }
  while (body[body.length - 1] === '') body.pop();
  if (body.length === 0) return [];
  return [
    'Deltas apply on top of Element styles (default), in the order listed; later values win per property.',
    '',
    ...body,
  ];
}

/** Config-space cap above which invalid-combination minimization is skipped. */
const MINIMIZE_SPACE_CAP = 4096;

function buildInvalidCombinations(spec: Rec, props: Rec, variants: Rec[]): string[] {
  const combos = (spec.invalidVariantCombinations ?? []) as Rec[];
  if (combos.length === 0) return [];

  // Normalize values to prop casing so pattern matching is exact.
  const normalized: Array<Map<string, string>> = combos.map(c => {
    const entries = Object.entries(c).map(
      ([k, v]) => [k, normalizePropValue(String(v), props[k] as Rec | undefined)] as [string, string],
    );
    return new Map(entries);
  });

  const minimized = minimizeInvalidCombinations(normalized, props, variants);
  const lines = minimized.map(m => `- ${code([...m].map(([k, v]) => `${k}: ${v}`).join(', '))}`);
  if (minimized.length < combos.length) {
    lines.push(
      '',
      `_Reduced from ${combos.length} spec entries; these patterns cover exactly the same configurations._`,
    );
  }
  return lines;
}

/**
 * Exact-cover minimization: an axis may be dropped from a combo only when every
 * configuration the reduced pattern matches is invalid according to the original
 * list. Deterministic (fixed axis and combo order); skipped for large config spaces.
 */
function minimizeInvalidCombinations(
  combos: Array<Map<string, string>>,
  props: Rec,
  variants: Rec[],
): Array<Map<string, string>> {
  const axes = variantAxes(props, variants);
  const axisValues = new Map<string, string[]>();
  for (const [key, p] of axes) {
    axisValues.set(key, p.type === 'boolean' ? ['true', 'false'] : ((p.enum ?? []) as unknown[]).map(String));
  }
  // Boolean props referenced only by invalid combinations still span the space.
  for (const combo of combos) {
    for (const key of combo.keys()) {
      if (axisValues.has(key)) continue;
      const p = props[key] as Rec | undefined;
      if (p?.type === 'boolean') axisValues.set(key, ['true', 'false']);
    }
  }

  let space = 1;
  for (const values of axisValues.values()) space *= values.length;
  if (axisValues.size === 0) space = 0;
  const comboKeysKnown = combos.every(c => [...c.keys()].every(k => axisValues.has(k)));
  if (space === 0 || space > MINIMIZE_SPACE_CAP || !comboKeysKnown) {
    // Fall back to plain subsumption (drop combos containing a shorter listed combo).
    const subsumed = new Set<number>();
    for (let i = 0; i < combos.length; i++) {
      for (let j = 0; j < combos.length; j++) {
        if (i === j || subsumed.has(i) || subsumed.has(j)) continue;
        if (combos[i].size < combos[j].size && [...combos[i]].every(([k, v]) => combos[j].get(k) === v)) {
          subsumed.add(j);
        }
      }
    }
    return combos.filter((_, i) => !subsumed.has(i));
  }

  // Enumerate the full configuration space once.
  const axisKeys = [...axisValues.keys()];
  let configs: Array<Map<string, string>> = [new Map()];
  for (const key of axisKeys) {
    const next: Array<Map<string, string>> = [];
    for (const partial of configs) {
      for (const value of axisValues.get(key)!) {
        next.push(new Map(partial).set(key, value));
      }
    }
    configs = next;
  }

  const matches = (pattern: Map<string, string>, config: Map<string, string>) =>
    [...pattern].every(([k, v]) => config.get(k) === v);
  const isInvalid = (config: Map<string, string>) => combos.some(c => matches(c, config));

  const reduced: Array<Map<string, string>> = [];
  for (const combo of combos) {
    let pattern = new Map(combo);
    let dropped = true;
    while (dropped) {
      dropped = false;
      for (const key of [...pattern.keys()]) {
        const candidate = new Map(pattern);
        candidate.delete(key);
        if (candidate.size === 0) continue;
        if (configs.filter(c => matches(candidate, c)).every(isInvalid)) {
          pattern = candidate;
          dropped = true;
          break;
        }
      }
    }
    reduced.push(pattern);
  }

  // Dedupe identical patterns and drop patterns subsumed by shorter ones, keeping first-occurrence order.
  const kept: Array<Map<string, string>> = [];
  for (const pattern of reduced) {
    const isDuplicate = kept.some(
      k => k.size === pattern.size && [...k].every(([key, v]) => pattern.get(key) === v),
    );
    if (isDuplicate) continue;
    kept.push(pattern);
  }
  const final: Array<Map<string, string>> = [];
  for (const pattern of kept) {
    const subsumedByOther = kept.some(
      other => other !== pattern && other.size < pattern.size && [...other].every(([k, v]) => pattern.get(k) === v),
    );
    if (!subsumedByOther) final.push(pattern);
  }
  return final;
}

function buildSubcomponents(subcomponents: Rec): string[] {
  const entries = Object.entries(subcomponents);
  if (entries.length === 0) return [];
  const rows = entries.map(([key, raw]) => {
    const sub = raw as Rec;
    const props = Object.keys((sub.props ?? {}) as Rec);
    return [
      `[${code(key)}](${key}/component.md)`,
      String(sub.title ?? '—'),
      props.length > 0 ? props.map(code).join(' ') : '—',
    ];
  });
  return table(['Subcomponent', 'Title', 'Props'], rows);
}

function buildExamples(spec: Rec, props: Rec): string[] {
  const body: string[] = [];
  const instanceExamples = (spec.instanceExamples ?? {}) as Rec;
  const slotContentExamples = (spec.slotContentExamples ?? {}) as Rec;

  if (Object.keys(instanceExamples).length > 0) {
    body.push('**Instance examples** — prop values that differ from the defaults. Full data: `examples.yaml`.', '');
    const rows: string[][] = [];
    for (const [name, raw] of Object.entries(instanceExamples)) {
      const ex = raw as Rec;
      const configs = (ex.propConfigurations ?? {}) as Rec;
      const nonDefault = Object.entries(configs).filter(([k, v]) => {
        const p = props[k] as Rec | undefined;
        return !p || !('default' in p) || String(p.default) !== String(v);
      });
      const summary =
        nonDefault.length > 0
          ? nonDefault.map(([k, v]) => `${k}: ${formatScalar(v)}`).join(', ')
          : '(all defaults)';
      rows.push([code(name), code(summary)]);
    }
    body.push(...table(['Example', 'Non-default configuration'], rows));
  }
  if (Object.keys(slotContentExamples).length > 0) {
    if (body.length > 0) body.push('');
    body.push(
      `**Slot content examples** — full element data in \`examples.yaml\`: ${Object.keys(slotContentExamples).map(code).join(' ')}`,
    );
  }
  return body;
}

function buildProvenance(spec: Rec): string[] {
  const metadata = (spec.metadata ?? {}) as Rec;
  const generator = (metadata.generator ?? {}) as Rec;
  const schema = (metadata.schema ?? {}) as Rec;
  const source = (metadata.source ?? {}) as Rec;

  const parts: string[] = [];
  if (metadata.author) parts.push(`author ${metadata.author}`);
  if (metadata.lastUpdated) parts.push(`updated ${metadata.lastUpdated}`);
  if (generator.name) parts.push(`generator ${generator.name}${generator.version ? ` v${generator.version}` : ''}`);
  if (schema.version) parts.push(`schema ${schema.version}`);
  if (source.nodeId) parts.push(`source node ${source.nodeId}`);
  return parts.length > 0 ? [parts.join(' · ')] : ['_No metadata._'];
}

// ---------------------------------------------------------------------------
// Value formatting
// ---------------------------------------------------------------------------

/** Flatten Sides-style objects (padding.top …) and effects groups one level; pass everything else through. */
function flattenStyles(styles: Rec): Array<[string, unknown]> {
  const out: Array<[string, unknown]> = [];
  for (const [prop, value] of Object.entries(styles)) {
    if (isSidesObject(value)) {
      for (const [side, sv] of Object.entries(value as Rec)) {
        out.push([`${prop}.${side}`, sv]);
      }
    } else if (
      prop === 'effects' &&
      typeof value === 'object' &&
      value !== null &&
      !Array.isArray(value) &&
      !isTokenRef(value)
    ) {
      for (const [kind, ev] of Object.entries(value as Rec)) {
        out.push([`${prop}.${kind}`, ev]);
      }
    } else {
      out.push([prop, value]);
    }
  }
  return out;
}

function isSidesObject(v: unknown): boolean {
  if (typeof v !== 'object' || v === null || Array.isArray(v)) return false;
  const keys = Object.keys(v as Rec);
  return keys.length > 0 && keys.every(k => ['top', 'end', 'bottom', 'start'].includes(k));
}

const COLOR_PROPS = new Set(['backgroundColor', 'textColor', 'strokes']);

function isColorValue(value: unknown, prop: string): boolean {
  if (isTokenRef(value)) return (value as Rec).$type === 'color';
  if (typeof value === 'string' && /^#[0-9a-fA-F]{3,8}$/.test(value)) return true;
  if (COLOR_PROPS.has(prop) && value !== undefined) return true;
  return false;
}

function formatValue(value: unknown): string {
  if (value === null) return 'unset';
  if (value === undefined) return '—';
  if (isTokenRef(value)) {
    const t = value as { $token: string; $type?: string; $extensions?: Rec };
    const raw = tokenRawValue(t);
    const qualifier = [t.$type, raw].filter(Boolean).join(', ');
    return `${code(t.$token)}${qualifier ? ` (${qualifier})` : ''}`;
  }
  if (Array.isArray(value)) {
    return value.map(v => formatValue(v)).join('; ');
  }
  if (typeof value === 'object') {
    const v = value as Rec;
    // JSON Pointer refs (e.g. instanceOf: { $ref: '#/subcomponents/x' }) render as the pointer basename.
    if (typeof v.$ref === 'string') {
      const segments = v.$ref.split('/');
      return code(segments[segments.length - 1]);
    }
    // Shadow-shaped objects render as a compact CSS-like string (offset-x offset-y blur spread color).
    if ('offsetX' in v || 'blur' in v) {
      const parts = [
        v.visible === false ? '(hidden)' : null,
        v.inset ? 'inset' : null,
        v.offsetX,
        v.offsetY,
        v.blur,
        v.spread,
        v.color,
      ]
        .filter(x => x !== null && x !== undefined)
        .map(String);
      return code(parts.join(' '));
    }
    const binding = extractBinding(value);
    if (binding) {
      if (!binding.condition) return `← ${code(binding.propName)}`;
      return `if ${binding.condition}${binding.outcome ? ` ${binding.outcome}` : ''}`;
    }
    // Inline typography objects render as `family style size/line-height`.
    if ('fontFamily' in v || 'fontSize' in v) {
      const size = [v.fontSize, v.lineHeight].filter(x => x !== undefined).join('/');
      const parts = [v.fontFamily, v.fontStyle, size].filter(x => x !== undefined && x !== '').map(String);
      return code(parts.join(' '));
    }
    return code(JSON.stringify(v));
  }
  return code(formatScalar(value));
}

/** Resolved raw value from $extensions["com.figma"].rawValue, when the token format carries it. */
function tokenRawValue(t: { $extensions?: Rec }): string | null {
  const raw = ((t.$extensions?.['com.figma'] as Rec | undefined) ?? {}).rawValue;
  if (raw === undefined || raw === null) return null;
  if (typeof raw === 'object') {
    const hex = (raw as Rec).hex;
    return typeof hex === 'string' ? hex : null;
  }
  return String(raw);
}

function formatScalar(value: unknown): string {
  if (value === null) return 'null';
  return String(value);
}

function formatConfiguration(configuration: Rec): string {
  const parts = Object.entries(configuration).map(([k, v]) => `${k}: ${v}`);
  return parts.length > 0 ? code(parts.join(', ')) : code('(default)');
}

// ---------------------------------------------------------------------------
// Markdown primitives
// ---------------------------------------------------------------------------

function table(headers: string[], rows: string[][]): string[] {
  const lines: string[] = [];
  lines.push(`| ${headers.join(' | ')} |`);
  lines.push(`|${headers.map(() => '---').join('|')}|`);
  for (const row of rows) {
    lines.push(`| ${row.map(cell => cell.replace(/\|/g, '\\|')).join(' | ')} |`);
  }
  return lines;
}

function code(s: string): string {
  return `\`${s}\``;
}

function plural(n: number, noun: string): string {
  return `${n} ${noun}${n === 1 ? '' : 's'}`;
}
